

typedef enum
{
	MESH_NOP, //
	MESH_CONNECTION_REQUEST, //
	MESH_CONNECTION_REQUEST_ACK,
	MESH_DISCONNECT_SERVER, //
	MESH_DISCONNECT_CLIENT,
	MESH_REQUEST_STATUS, //
	MESH_REQUEST_STATUS_ACK,
	MESH_START_IMAGE_TRANSFER, // 
	MESH_START_IMAGE_TRANSFER_ACK,
	MESH_DATA_IMAGE_PACKET, //
	MESH_DATA_IMAGE_PACKET_ACK,
	MESH_DATA_IMAGE_REQUEST, 
	MESH_IMAGE_TRANSFER_SUCCESS, //
	MESH_IMAGE_TRANSFER_SUCCESS_ACK,
	MESH_IMAGE_ACTIVATE, // 
	MESH_IMAGE_ACTIVATE_ACK,
	MESH_CLIENT_ERROR
} mesh_client_code;

typedef enum
{
	MESH_BROADCAST_NOP,
	MESH_BROADCAST_STATUS,
	MESH_BROADCAST_CLIENT_DIRECTION
} mesh_broadcast_code;
